## <u> ASSIGNMENT 3 : PRINCIPAL COMPONENT ANALYSIS </u>

### Question 2  :
*  Yale faces data set is an image data set of 15 subjects that is used for testing
facial recognition methods. There are six different grayscale images of each
subject with different facial expressions. The resolution of each image is 243 x
320 pixels.

In [1]:
import scipy.io
from scipy.stats.distributions import chi2
import scipy.linalg as slinal
import numpy as np 
import numpy.linalg as linal
import pandas as pd 
import sympy as sp

In [2]:
mat = scipy.io.loadmat('cov.mat')
COV = np.matrix(mat['covF'])

In [3]:
eigenvalues, eigenvectors = linal.eig(COV)

print("EIGENVALUES AND EIGENVECTORS :")
print("-----------------------------------------------------------------------------------------------------------")

for eig in eigenvalues : 
    index = np.where(eigenvalues == eig)[0][0] 
    print (f"{index + 1} |", np.round(eig,5), end='\t')
    print ("| Eigenvector :", *eigenvectors[:,index].T, sep='\t')

print("-----------------------------------------------------------------------------------------------------------")

EIGENVALUES AND EIGENVECTORS :
-----------------------------------------------------------------------------------------------------------
1 | 8.67843	| Eigenvector :	[[ 0.12277361 -0.58112169  0.06381017  0.18830573 -0.76976835  0.12308585]]
2 | 3.61457	| Eigenvector :	[[-0.41906663 -0.50530519 -0.17421795 -0.59463921  0.08736405 -0.42127148]]
3 | 0.96194	| Eigenvector :	[[-0.43691843  0.14820627  0.70895487  0.26900453 -0.1277576  -0.44253219]]
4 | 0.01035	| Eigenvector :	[[-0.64645944  0.41966047 -0.28325179 -0.13664477 -0.41880558  0.36286885]]
5 | 0.00974	| Eigenvector :	[[-0.44346887 -0.45126681 -0.0168924   0.47207596  0.45062758  0.41651812]]
6 | 0.00996	| Eigenvector :	[[ 0.06194869 -0.07240512  0.61841929 -0.54502681  0.0709851   0.55351994]]
-----------------------------------------------------------------------------------------------------------


$$ Az^{*}_{i} = 0 $$
* $z^{*}_{i} : \textbf{True value of measurements of i th sample}$ 
* $A : \textbf{mxp constraint matrix} $ 
* $p : \textbf{Number of Variables} $ 
* $N : \textbf{Number of Samples in data Matrix} $ 
* $m : \textbf{Number of Contraints}$ 

$$ H_0 : \lambda_{N,p-d+1} = \lambda_{N,p-d+2} = ... = \lambda_{N,p} $$
$$ H_1 : \textbf{at least two smallest d eigenvalues are unequal} $$

* The Statistic to test the Hypothesis is : 
$$ \tau = n' \cdot \left[ d\cdot \ln{\overline{l}} - \sum_{j = p-d+1}^{j = p} \ln{l_{N,j}}\right] $$
$$ \overline{l} = \frac{1}{d}\cdot \sum_{j = p-d+1}^{j = p} l_{N,j}$$
$$ n' = N - \frac{2p+11}{6} $$

* Here $l_{N,j}$ is the jth eigenvalue of $S_{z_s}$
* The NULL HYPOTHESIS is rejected if the $\tau \ge \chi^2_{\nu,\alpha}$
* Here $\chi^2$ is the chi-square distirbution with $\nu$ degrees of freedom, computed as $\nu = \frac{1}{2}\cdot (d+2)\cdot (d-1)$


In [4]:
p = 6
d = p-1
N = 1000

print("STATISTICAL TESTING :")
while True : 
    n_dash = N - (2*p+11)/6
    l_dash = eigenvalues[ p-d : ].sum()/d 

    tau    = n_dash * ( d * np.log(l_dash) - np.log(eigenvalues[ p-d : ]).sum())

    fdom   = 0.5*(d+2)*(d-1)
    chi    = chi2.ppf(0.95, df=fdom)

    print("-----------------------------------------------------")
    print(f"Chi-square at 95% and {int(fdom)} dof \t\t: {np.round(chi,4)}")
    print(f"The computed statistic value is \t: {np.round(tau,4)}")

    if (tau <= chi) : 
        break 
    else : 
        d = d - 1 

print("-----------------------------------------------------",end='\n\n')
print (f"Number of constraints after performing the above test is : {d}")


STATISTICAL TESTING :
-----------------------------------------------------
Chi-square at 95% and 14 dof 		: 23.6848
The computed statistic value is 	: 12109.1004
-----------------------------------------------------
Chi-square at 95% and 9 dof 		: 16.919
The computed statistic value is 	: 8241.373
-----------------------------------------------------
Chi-square at 95% and 5 dof 		: 11.0705
The computed statistic value is 	: 0.951
-----------------------------------------------------

Number of constraints after performing the above test is : 3


In [5]:
print("EIGENVALUES AND EIGENVECTORS AFTER PERFORMING STATISTIC TESTING:")
print("-----------------------------------------------------------------------------------------------------------")

for eig in eigenvalues[d:] : 
    index = np.where(eigenvalues == eig)[0][0] 
    print (f"{index + 1} |", np.round(eig,5), end='\t')
    print ("| Eigenvector :", *eigenvectors[:,index].T, sep='\t')

print("-----------------------------------------------------------------------------------------------------------")

EIGENVALUES AND EIGENVECTORS AFTER PERFORMING STATISTIC TESTING:
-----------------------------------------------------------------------------------------------------------
4 | 0.01035	| Eigenvector :	[[-0.64645944  0.41966047 -0.28325179 -0.13664477 -0.41880558  0.36286885]]
5 | 0.00974	| Eigenvector :	[[-0.44346887 -0.45126681 -0.0168924   0.47207596  0.45062758  0.41651812]]
6 | 0.00996	| Eigenvector :	[[ 0.06194869 -0.07240512  0.61841929 -0.54502681  0.0709851   0.55351994]]
-----------------------------------------------------------------------------------------------------------


* The correct number of linearly independent constraints have been determined as the system has only 3 linearly independent constraints and it is the same result we obtained by performing Statistic test

In [6]:
A = np.matrix([[1, -1, 1, 0, 1, 0],[0,1,0,-1,-1,0],[0,0,-1,1,0,-1]])
eigenvectors = np.array(eigenvectors)
A_estimate = np.array([eigenvectors[:,3].T,eigenvectors[:,4].T,eigenvectors[:,5].T])


print(-A, '\n\n', A_estimate)

[[-1  1 -1  0 -1  0]
 [ 0 -1  0  1  1  0]
 [ 0  0  1 -1  0  1]] 

 [[-0.64645944  0.41966047 -0.28325179 -0.13664477 -0.41880558  0.36286885]
 [-0.44346887 -0.45126681 -0.0168924   0.47207596  0.45062758  0.41651812]
 [ 0.06194869 -0.07240512  0.61841929 -0.54502681  0.0709851   0.55351994]]


In [7]:
angles = slinal.subspace_angles(A,A_estimate)

print("-----------------------------")
print(f"subspace angle 1 : {np.round(angles[0],20)}")
print(f"subspace angle 2 : {np.round(angles[1],20)}")
print(f"subspace angle 3 : {np.round(angles[2],20)}")
print("-----------------------------")

-----------------------------
subspace angle 1 : 5.0037e-16
subspace angle 2 : 1.9008e-16
subspace angle 3 : 1.6906e-16
-----------------------------


In [8]:
print(A_estimate)

linal.det(A_estimate[:,[1,2,3]])

[[-0.64645944  0.41966047 -0.28325179 -0.13664477 -0.41880558  0.36286885]
 [-0.44346887 -0.45126681 -0.0168924   0.47207596  0.45062758  0.41651812]
 [ 0.06194869 -0.07240512  0.61841929 -0.54502681  0.0709851   0.55351994]]


-0.0010032001427014421

In [43]:
from itertools import combinations

comb = list(combinations([0,1,2,3,4,5],3))
values = {}

for combination in comb :
    values[combination] = np.round(linal.det(A_estimate[:,combination]),4)

sorted_by_determinant = sorted(values.items(), key=lambda item: item[1])

print('------------------------------')
for value in sorted_by_determinant : 
    # print(f"{value[0]} : {value[1]}")
    vals, vecs = linal.eig(A[:,value[0]])
    print(f'{value[0]} : {np.round(np.abs(vals.max()/vals.min()),3)}')

print('------------------------------')


------------------------------
(0, 1, 3) : 1.0
(0, 3, 4) : 1.0
(2, 3, 5) : 1.0
(0, 4, 5) : 1.0
(1, 2, 5) : 0.382
(0, 3, 5) : 1.0
(2, 4, 5) : 1.0
(0, 2, 5) : 1.0
(1, 2, 3) : 1.0
(0, 1, 4) : inf
(1, 3, 4) : 0.0
(1, 2, 4) : 0.5
(1, 4, 5) : 0.0
(2, 3, 4) : 463564461130729.56
(3, 4, 5) : 1.0
(1, 3, 5) : 1.0
(0, 1, 5) : 1.0
(0, 2, 4) : 1.0
(0, 1, 2) : 1.0
(0, 2, 3) : 2.618
------------------------------


/tmp/ipykernel_25606/2458863887.py:15: RuntimeWarning: divide by zero encountered in double_scalars
  print(f'{value[0]} : {np.round(np.abs(vals.max()/vals.min()),3)}')


* From the above list of condition number versus their corresponding Flow rates chosen as the dependent variables we can observe that 2 combinations of the 20 are having very high condition number
* Hence we cannot have variables $F_1, F_2$ and $F_5$ or $F_3, F_4$ and $F_5$ as dependent variables as their condition numbers are much greater than 1000

In [39]:
A_dependent_estimate   = A_estimate[:,[0,1,2]]
A_independent_estimate = A_estimate[:,[3,4,5]]

A_dependent   = A[:,[0,1,2]]
A_independent = A[:,[3,4,5]]

regression_estimate = (A_dependent_estimate**-1)*A_independent_estimate
regression          = (A_dependent**-1)*A_independent

print(np.abs(regression_estimate-regression))

[[2.11374084e-01 9.97962894e-01 2.81082290e-01]
 [6.45075439e-02 1.41653123e-03 2.46571295e+01]
 [7.79803597e+00 9.80387939e-01 1.04943933e-01]]
