In [49]:
import scipy.io
import numpy as np
import matplotlib.pyplot as plt

from sklearn.linear_model import LinearRegression  

In [2]:
mat = scipy.io.loadmat('Inorfull.mat')

In [4]:
Concentrations = mat['CONC']
Absorbance     = mat['DATA']

In [70]:
A = Absorbance[0::5,[47,53,105]]
C = Concentrations[0::5]

A = A - A.mean(axis=0)
C = C - C.mean(axis=0)

In [71]:
B = ((A.T@A)**-1)@A.T@C

In [51]:
model = LinearRegression().fit(A,C)

In [72]:
A = Absorbance[0::5,[47,53,105]]
A@B

array([[0.04196824, 0.22334609, 0.08540414],
       [0.06446554, 0.40004938, 0.10091136],
       [0.08582132, 0.57148558, 0.11366337],
       [0.06832702, 0.30795985, 0.16862417],
       [0.09337283, 0.50057797, 0.18806615],
       [0.11537134, 0.67387415, 0.20295698],
       [0.09986039, 0.42506509, 0.25974151],
       [0.12155048, 0.59950669, 0.27252262],
       [0.14261035, 0.76483771, 0.28708283],
       [0.06795294, 0.35601354, 0.14126376],
       [0.09268848, 0.54545609, 0.16088347],
       [0.11617482, 0.72689601, 0.17868293],
       [0.09701807, 0.45631143, 0.22930989],
       [0.1217088 , 0.6478002 , 0.24762404],
       [0.14348925, 0.81861694, 0.26277311],
       [0.1263796 , 0.56016763, 0.31690584],
       [0.15123806, 0.74891054, 0.33749626],
       [0.17344239, 0.92544186, 0.35166867],
       [0.09733134, 0.50636007, 0.2042304 ],
       [0.12149357, 0.69511757, 0.22142812],
       [0.14255648, 0.86255783, 0.23488109],
       [0.12634131, 0.60977087, 0.29035444],
       [0.

In [59]:
C

array([[0.00305775, 0.01571527, 0.0068796 ],
       [0.00305775, 0.01571527, 0.02063881],
       [0.00305775, 0.01571527, 0.03439802],
       [0.00305775, 0.0471458 , 0.0068796 ],
       [0.00305775, 0.0471458 , 0.02063881],
       [0.00305775, 0.0471458 , 0.03439802],
       [0.00305775, 0.07857634, 0.0068796 ],
       [0.00305775, 0.07857634, 0.02063881],
       [0.00305775, 0.07857634, 0.03439802],
       [0.00917326, 0.01571527, 0.0068796 ],
       [0.00917326, 0.01571527, 0.02063881],
       [0.00917326, 0.01571527, 0.03439802],
       [0.00917326, 0.0471458 , 0.0068796 ],
       [0.00917326, 0.0471458 , 0.02063881],
       [0.00917326, 0.0471458 , 0.03439802],
       [0.00917326, 0.07857634, 0.0068796 ],
       [0.00917326, 0.07857634, 0.02063881],
       [0.00917326, 0.07857634, 0.03439802],
       [0.01528877, 0.01571527, 0.0068796 ],
       [0.01528877, 0.01571527, 0.02063881],
       [0.01528877, 0.01571527, 0.03439802],
       [0.01528877, 0.0471458 , 0.0068796 ],
       [0.

In [58]:
model.predict(A)

array([[0.00344285, 0.01502989, 0.00689501],
       [0.00201775, 0.01928518, 0.02199012],
       [0.00337706, 0.01401631, 0.03392095],
       [0.00292182, 0.04706427, 0.0064878 ],
       [0.00309467, 0.04738835, 0.02084151],
       [0.00289315, 0.04773696, 0.03439427],
       [0.00339028, 0.07804302, 0.00701744],
       [0.00435814, 0.07388711, 0.01962186],
       [0.00285864, 0.07840246, 0.03391859],
       [0.00878332, 0.01620195, 0.00700119],
       [0.00977261, 0.01418891, 0.0201907 ],
       [0.00879973, 0.01779748, 0.03497983],
       [0.00866368, 0.04837039, 0.00702814],
       [0.00998765, 0.04472365, 0.02016211],
       [0.00876989, 0.0484068 , 0.03456734],
       [0.00928571, 0.07793672, 0.0066081 ],
       [0.00917376, 0.07974323, 0.0208231 ],
       [0.00921345, 0.07894031, 0.03446429],
       [0.01601931, 0.01373563, 0.00588526],
       [0.01514646, 0.01652836, 0.02125143],
       [0.01478094, 0.01701707, 0.0346214 ],
       [0.01563729, 0.04582914, 0.0066487 ],
       [0.