In [1]:
import numpy as np

In [2]:
Ai = np.array([[0.8258],[0.2833]])
Ad = np.array([[0.2331, -0.5135],[-0.9588, 0.01992]])

In [32]:
value = (Ad**-1)@Ai*-5

In [9]:
cov = np.array([[7,21,34],[21,64,102],[34,102,186]])

In [11]:
vals, vecs = np.linalg.eig(cov)

In [28]:
Ad_ = vecs[:,[2,1]].T[:,[0,2]]
Ai_ = vecs[:,[2,1]].T[:,[1]]

In [49]:
(Ad_**-1)@Ai_*-5

array([[-14.9665483 ],
       [-66.13863995]])

In [30]:
vecs[:,[2,1]].T

array([[-0.23300092, -0.8258747 ,  0.51346037],
       [ 0.95890336, -0.28302089, -0.02008808]])

In [46]:
Ad**-1@Ai*-5

array([[-14.95490775],
       [-66.80301305]])

In [47]:
(Ad_**-1)@Ai_*-5

array([[-14.9665483 ],
       [-66.13863995]])